version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
    ports:
      - "4013:4013"
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
