name: Set Env Vars

on:
  push:
  pull_request:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: g2idocker/auth:latest
          secrets: |
              "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}"
